[features]
seeds = false
[programs.localnet]
spin = "HHuEhMpSBPucPagawyqGwbM9PRJESbGCw2ZmcdrWs3UY"

[programs.devnet]
spin = "HHuEhMpSBPucPagawyqGwbM9PRJESbGCw2ZmcdrWs3UY"

[programs.mainnet]
spin = "HHuEhMpSBPucPagawyqGwbM9PRJESbGCw2ZmcdrWs3UY"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
